"""
new-openings-data.py — Generate comprehensive line data for all 10 remaining openings.
Outputs data/new-openings-lines.json with full metadata.
Then run generate-nodes.py to add node trees.
"""
import json
from pathlib import Path

OPENINGS = {}

# ═══════════════════════════════════════════════════════════════════════════════
# 1. LONDON SYSTEM (White)
# ═══════════════════════════════════════════════════════════════════════════════
OPENINGS["london-system"] = {
    "openingName": "London System",
    "lineCount": 10,
    "lines": [
        {
            "openingSlug": "london-system",
            "slug": "london-main-setup",
            "title": "Main Setup: d4-Nf3-Bf4",
            "chapterName": "Core System",
            "eco": "D02",
            "color": "white",
            "pgn": "1. d4 d5 2. Nf3 Nf6 3. Bf4 e6 4. e3 Bd6 5. Bg3 O-O 6. Bd3 c5 7. c3",
            "difficulty": "beginner",
            "commonness": 95,
            "priority": 95,
            "isMustKnow": True,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "The foundational London System position. White develops Bf4 before e3, maintaining a solid pawn structure.",
            "strategicGoal": "Establish the London pyramid (d4-e3-c3) with Bf4 and Bd3. Aim for a kingside attack or central break with e4.",
            "commonOpponentMistake": "Black plays ...Bd6 too early without ...c5, allowing White to maintain the bishop pair after Bxd6.",
            "punishmentIdea": "After premature ...Bd6, exchange with Bxd6 Qxd6 then play Nbd2-e5 with a strong outpost.",
            "hintText": "Always develop Bf4 before e3 — this is the key move order that defines the London.",
            "pawnStructure": "London pyramid",
            "themes": ["central-control", "piece-activity"],
            "sortOrder": 10
        },
        {
            "openingSlug": "london-system",
            "slug": "london-vs-c5-early",
            "title": "vs ...c5: Early Challenge",
            "chapterName": "Black Challenges",
            "eco": "D02",
            "color": "white",
            "pgn": "1. d4 d5 2. Nf3 Nf6 3. Bf4 c5 4. e3 Nc6 5. c3 e6 6. Nbd2 Bd6 7. Bg3 O-O 8. Bd3",
            "difficulty": "intermediate",
            "commonness": 85,
            "priority": 85,
            "isMustKnow": True,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "Black challenges the center early with ...c5. White maintains the pyramid and prepares Ne5.",
            "strategicGoal": "Keep the d4-c3-e3 structure intact. After Nbd2, reroute to e5 or prepare e4 break.",
            "commonOpponentMistake": "Black captures cxd4 too early, opening the c-file for White's rook.",
            "punishmentIdea": "After ...cxd4 exd4, White gets open e-file and active pieces. Rc1 pressures c7.",
            "hintText": "Don't rush to capture on c5. Keep tension and develop with Nbd2, then decide on Ne5 or e4.",
            "pawnStructure": "London pyramid",
            "themes": ["central-control", "positional-squeeze"],
            "sortOrder": 20
        },
        {
            "openingSlug": "london-system",
            "slug": "london-vs-bf5-mirror",
            "title": "vs ...Bf5: Mirror London",
            "chapterName": "Black Challenges",
            "eco": "D02",
            "color": "white",
            "pgn": "1. d4 d5 2. Nf3 Nf6 3. Bf4 Bf5 4. e3 e6 5. Bd3 Bxd3 6. Qxd3 Bd6 7. Bxd6 Qxd6 8. Nbd2 O-O 9. O-O",
            "difficulty": "intermediate",
            "commonness": 70,
            "priority": 70,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "Black mirrors with ...Bf5, leading to a symmetrical structure. White aims for a slight edge with better piece coordination.",
            "strategicGoal": "Exchange bishops on d3, then use the half-open c-file and Ne5 outpost for pressure.",
            "commonOpponentMistake": "Black allows Ne5 without challenging it, giving White a dominant knight.",
            "punishmentIdea": "After Ne5, White dominates the center. If Black doesn't play ...Nd7 to challenge, Ne5 becomes permanent.",
            "hintText": "In mirror positions, play for Ne5 — the knight on e5 is worth more than the bishop pair here.",
            "pawnStructure": "Symmetrical center",
            "themes": ["piece-activity", "positional-squeeze"],
            "sortOrder": 30
        },
        {
            "openingSlug": "london-system",
            "slug": "london-kingside-attack",
            "title": "Kingside Attack: h4-h5",
            "chapterName": "Attacking Plans",
            "eco": "D02",
            "color": "white",
            "pgn": "1. d4 d5 2. Nf3 Nf6 3. Bf4 e6 4. e3 Bd6 5. Bg3 O-O 6. Bd3 Nbd7 7. Nbd2 Re8 8. Qe2 e5 9. dxe5 Nxe5 10. Nxe5 Bxe5 11. Bxe5 Rxe5 12. h4",
            "difficulty": "intermediate",
            "commonness": 60,
            "priority": 75,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "attacking",
            "lineSummary": "White launches a kingside pawn storm with h4-h5, targeting Black's castled king.",
            "strategicGoal": "After exchanging dark-squared bishops, push h4-h5 to open lines against Black's king.",
            "commonOpponentMistake": "Black ignores the h-pawn advance and doesn't play ...h6 to slow it down.",
            "punishmentIdea": "h5-h6 creates permanent weaknesses around Black's king. Qe2-e5 with Ng5 threats.",
            "hintText": "The h4-h5 plan works best after the dark-squared bishops are exchanged — Black's king becomes vulnerable.",
            "pawnStructure": "Open center",
            "themes": ["kingside-attack", "piece-activity"],
            "sortOrder": 40
        },
        {
            "openingSlug": "london-system",
            "slug": "london-vs-kings-indian",
            "title": "vs King's Indian Setup",
            "chapterName": "Black Setups",
            "eco": "A48",
            "color": "white",
            "pgn": "1. d4 Nf6 2. Nf3 g6 3. Bf4 Bg7 4. e3 O-O 5. Be2 d6 6. h3 Nbd7 7. O-O",
            "difficulty": "beginner",
            "commonness": 80,
            "priority": 80,
            "isMustKnow": True,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "When Black plays a King's Indian setup, White develops solidly with Be2 and h3 to prevent ...Nh5.",
            "strategicGoal": "Solid development with Be2 (not Bd3 which blocks d-file). h3 prevents ...Nh5 harassing the bishop.",
            "commonOpponentMistake": "Black plays ...Nh5 without h3 being played, winning the bishop pair.",
            "punishmentIdea": "If Black plays ...Nh5 after h3, the knight is misplaced. White continues with c4 and Nc3 for space.",
            "hintText": "Against fianchetto setups, play Be2 (not Bd3) and always include h3 to protect your bishop.",
            "pawnStructure": "London vs KID",
            "themes": ["central-control", "space-advantage"],
            "sortOrder": 50
        },
        {
            "openingSlug": "london-system",
            "slug": "london-vs-nh5",
            "title": "vs ...Nh5: Bishop Challenge",
            "chapterName": "Black Challenges",
            "eco": "D02",
            "color": "white",
            "pgn": "1. d4 d5 2. Nf3 Nf6 3. Bf4 Nh5 4. Bg5 h6 5. Bh4 g5 6. Bg3 Nxg3 7. hxg3",
            "difficulty": "intermediate",
            "commonness": 65,
            "priority": 70,
            "isMustKnow": True,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "Black immediately challenges the London bishop with ...Nh5. White retreats to g5/g3 and gets the h-file.",
            "strategicGoal": "Allow the bishop exchange on g3. After hxg3, White gets the open h-file for a kingside attack.",
            "commonOpponentMistake": "Black weakens kingside with ...g5 and ...h6 trying to win the bishop, creating permanent holes.",
            "punishmentIdea": "After hxg3, the open h-file combined with Black's weakened kingside gives White a lasting attack.",
            "hintText": "Don't fear ...Nh5. After Bg5-h4-g3 Nxg3 hxg3, the open h-file is compensation for the bishop.",
            "pawnStructure": "Open h-file",
            "themes": ["kingside-attack", "piece-activity"],
            "sortOrder": 60
        },
        {
            "openingSlug": "london-system",
            "slug": "london-e4-break",
            "title": "Central Break: e3-e4",
            "chapterName": "Attacking Plans",
            "eco": "D02",
            "color": "white",
            "pgn": "1. d4 d5 2. Nf3 Nf6 3. Bf4 e6 4. e3 Be7 5. Bd3 O-O 6. Nbd2 c5 7. c3 Nc6 8. O-O Qb6 9. Qe2 Bd7 10. e4",
            "difficulty": "intermediate",
            "commonness": 70,
            "priority": 75,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "White prepares the e4 central break, the most ambitious plan in the London System.",
            "strategicGoal": "Prepare e4 with Nbd2, Qe2, and O-O. The break opens the position favorably for White's active pieces.",
            "commonOpponentMistake": "Black doesn't prevent e4 with ...e5 or ...c4, allowing White to seize the center.",
            "punishmentIdea": "After e4 dxe4 Nxe4, White has a strong center and active pieces. Nxf6+ damages Black's structure.",
            "hintText": "The e4 break is the London's most powerful plan. Prepare it with Nbd2 and Qe2 before pushing.",
            "pawnStructure": "Open center",
            "themes": ["central-control", "piece-activity"],
            "sortOrder": 70
        },
        {
            "openingSlug": "london-system",
            "slug": "london-trap-qb6",
            "title": "Trap: ...Qb6 b2 Poison",
            "chapterName": "Traps",
            "eco": "D02",
            "color": "white",
            "pgn": "1. d4 d5 2. Nf3 Nf6 3. Bf4 c5 4. e3 Qb6 5. Nc3 Qxb2 6. Nb5 Na6 7. Rb1 Qa3 8. Nc7+",
            "difficulty": "beginner",
            "commonness": 50,
            "priority": 80,
            "isMustKnow": True,
            "isTrap": True,
            "lineType": "trap",
            "lineSummary": "A classic London trap where Black grabs the b2 pawn and gets punished with Nc7+ forking king and rook.",
            "strategicGoal": "Allow ...Qxb2 to lure the queen offside, then Nb5-c7+ wins the exchange.",
            "commonOpponentMistake": "Black grabs b2 thinking it's free, not seeing the Nb5-Nc7+ fork.",
            "punishmentIdea": "After ...Qxb2, Nb5 threatens Nc7+. The queen is trapped on the queenside while White forks.",
            "hintText": "If Black plays ...Qb6 threatening b2, don't defend it — let them take and punish with Nb5!",
            "pawnStructure": "London pyramid",
            "themes": ["tactical-complications", "gambit-play"],
            "sortOrder": 80
        },
        {
            "openingSlug": "london-system",
            "slug": "london-vs-dutch-setup",
            "title": "vs Dutch Setup: ...f5",
            "chapterName": "Black Setups",
            "eco": "A45",
            "color": "white",
            "pgn": "1. d4 f5 2. Nf3 Nf6 3. Bf4 e6 4. e3 Be7 5. Bd3 O-O 6. O-O d6 7. Nbd2 Qe8 8. c4",
            "difficulty": "intermediate",
            "commonness": 55,
            "priority": 60,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "Against the Dutch setup, White develops normally and aims for c4 to challenge Black's center.",
            "strategicGoal": "Develop solidly, then break with c4 to exploit the weakened e5 square and Black's light-square holes.",
            "commonOpponentMistake": "Black plays ...f5 without controlling e5, allowing White's knight to dominate on e5.",
            "punishmentIdea": "Ne5 is a dream square. After c4 and Ne5, White dominates the light squares permanently.",
            "hintText": "Against the Dutch, aim for Ne5 and c4. Black's f5 pawn weakens e5 and the a2-g8 diagonal.",
            "pawnStructure": "London vs Dutch",
            "themes": ["positional-squeeze", "space-advantage"],
            "sortOrder": 90
        },
        {
            "openingSlug": "london-system",
            "slug": "london-vs-grunfeld-setup",
            "title": "vs Grunfeld Setup: ...g6 ...d5",
            "chapterName": "Black Setups",
            "eco": "D02",
            "color": "white",
            "pgn": "1. d4 Nf6 2. Nf3 d5 3. Bf4 g6 4. e3 Bg7 5. Be2 O-O 6. O-O c5 7. c3 Nc6 8. Nbd2",
            "difficulty": "beginner",
            "commonness": 70,
            "priority": 65,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "Against a Grunfeld-like setup with ...g6 and ...d5, White plays Be2 and maintains the solid pyramid.",
            "strategicGoal": "Solid development with Be2 (avoiding ...Nh5 issues). Aim for Ne5 and e4 break when ready.",
            "commonOpponentMistake": "Black fianchettoes without challenging the center, allowing White to build up slowly.",
            "punishmentIdea": "White slowly builds with Nbd2-e5 and prepares e4. The Bg7 bites on granite (c3-d4 chain).",
            "hintText": "Against fianchetto + ...d5, use Be2 (not Bd3). The bishop is safer and supports e4 later.",
            "pawnStructure": "London vs Grunfeld",
            "themes": ["central-control", "positional-squeeze"],
            "sortOrder": 100
        }
    ]
}

# ═══════════════════════════════════════════════════════════════════════════════
# 2. VIENNA GAME (White) — distinct from Vienna Gambit
# ═══════════════════════════════════════════════════════════════════════════════
OPENINGS["vienna-game"] = {
    "openingName": "Vienna Game",
    "lineCount": 10,
    "lines": [
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-main",
            "title": "Main Line: 2.Nc3 Nf6 3.g3",
            "chapterName": "Core System",
            "eco": "C25",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 Nf6 3. g3 d5 4. exd5 Nxd5 5. Bg2 Nxc3 6. bxc3 Bd6 7. Nf3",
            "difficulty": "intermediate",
            "commonness": 70,
            "priority": 75,
            "isMustKnow": True,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "The quiet Vienna with g3 — White fianchettoes and aims for long-term pressure on the long diagonal.",
            "strategicGoal": "Fianchetto the bishop to g2, open the center, and use the long diagonal for pressure.",
            "commonOpponentMistake": "Black plays ...Be6 blocking the diagonal, but after d3 and Ng5 the bishop is harassed.",
            "punishmentIdea": "After Bg2, the long diagonal becomes a weapon. d3 + Ng5 can target f7 or force concessions.",
            "hintText": "The g3 Vienna is positional — fianchetto first, then decide between f4 or d3 based on Black's setup.",
            "pawnStructure": "Open center",
            "themes": ["piece-activity", "central-control"],
            "sortOrder": 10
        },
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-bc4-setup",
            "title": "Bc4 Setup: Italian-Vienna Hybrid",
            "chapterName": "Core System",
            "eco": "C26",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 Nf6 3. Bc4 Bc5 4. d3 d6 5. f4 O-O 6. Nf3",
            "difficulty": "intermediate",
            "commonness": 75,
            "priority": 80,
            "isMustKnow": True,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "A hybrid between the Vienna and Italian — Bc4 targets f7 while Nc3 supports f4.",
            "strategicGoal": "Develop Bc4 targeting f7, then push f4 to open the f-file for a kingside attack.",
            "commonOpponentMistake": "Black castles into the f4 attack without preparing ...d5 counterplay.",
            "punishmentIdea": "f4-f5 with Bc4 pointing at f7 creates devastating kingside pressure. Ng5 adds to the attack.",
            "hintText": "Bc4 + f4 is the aggressive Vienna plan. Develop the knight to f3 last so f4 isn't blocked.",
            "pawnStructure": "King's Gambit structure",
            "themes": ["kingside-attack", "tactical-complications"],
            "sortOrder": 20
        },
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-vs-nc6",
            "title": "vs 2...Nc6: Symmetrical",
            "chapterName": "Black Responses",
            "eco": "C25",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 Nc6 3. Bc4 Nf6 4. d3 Bb4 5. Nge2 d5 6. exd5 Nxd5 7. O-O",
            "difficulty": "intermediate",
            "commonness": 70,
            "priority": 70,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "When Black plays ...Nc6 instead of ...Nf6, the game takes on a more symmetrical character.",
            "strategicGoal": "Develop with Bc4 and Nge2 (keeping f4 option). After ...d5, recapture gives White active play.",
            "commonOpponentMistake": "Black plays ...Bb4 pinning but after a3 the bishop must retreat, losing time.",
            "punishmentIdea": "After a3 Bd6, White has gained a tempo and can play f4 with a strong initiative.",
            "hintText": "Against ...Nc6, develop Nge2 (not Nf3) to keep the f-pawn free for f4 later.",
            "pawnStructure": "Open center",
            "themes": ["piece-activity", "central-control"],
            "sortOrder": 30
        },
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-frankenstein-dracula",
            "title": "Frankenstein-Dracula: 3.Bc4 Nxe4",
            "chapterName": "Sharp Lines",
            "eco": "C27",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 Nf6 3. Bc4 Nxe4 4. Qh5 Nd6 5. Bb3 Nc6 6. Nb5 g6 7. Qf3 f5 8. Qd5 Qe7 9. Nxc7+ Kd8 10. Nxa8",
            "difficulty": "advanced",
            "commonness": 40,
            "priority": 65,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "sharp",
            "lineSummary": "The wild Frankenstein-Dracula variation — Black grabs e4 and both sides play for the initiative.",
            "strategicGoal": "After Qh5 and Nb5, aim for Nxc7+ winning the exchange. The resulting positions are complex but favorable.",
            "commonOpponentMistake": "Black plays ...Nc6 too early allowing Nb5 with tempo on c7.",
            "punishmentIdea": "Nb5 threatens Nxc7+ forking king and rook. Even if Black defends, White gets material.",
            "hintText": "After 3...Nxe4, play Qh5! immediately. The threat of Qxf7# forces Black into awkward defense.",
            "pawnStructure": "Chaotic",
            "themes": ["tactical-complications", "gambit-play"],
            "sortOrder": 40
        },
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-vs-d5-counter",
            "title": "vs 2...d5: Center Counter",
            "chapterName": "Black Responses",
            "eco": "C25",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 d5 3. exd5 Qxd5 4. Bc4 Qd8 5. Nf3 Nc6 6. O-O Nf6 7. d3 Be7 8. Bg5",
            "difficulty": "beginner",
            "commonness": 55,
            "priority": 60,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "Black plays an early ...d5 counter. White develops rapidly and gets a slight lead in development.",
            "strategicGoal": "Develop quickly with Bc4, Nf3, O-O. Black loses time with the queen and White gets initiative.",
            "commonOpponentMistake": "Black keeps the queen on d5 too long, allowing Nc3 with tempo.",
            "punishmentIdea": "After ...Qd5, Bc4 attacks the queen again. Black loses 2-3 tempi retreating.",
            "hintText": "Against early ...d5, just develop naturally. Black's queen moves waste time and you get ahead.",
            "pawnStructure": "Open center",
            "themes": ["piece-activity", "central-control"],
            "sortOrder": 50
        },
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-mieses",
            "title": "Mieses Variation: 3.d3",
            "chapterName": "Core System",
            "eco": "C25",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 Nc6 3. d3 Nf6 4. f4 d5 5. fxe5 Nxe4 6. Nf3 Bg4 7. Be2",
            "difficulty": "intermediate",
            "commonness": 50,
            "priority": 55,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "The Mieses variation with d3 — a slower buildup that keeps options for both f4 and g3 plans.",
            "strategicGoal": "Play d3 first to keep flexibility, then choose between f4 (aggressive) or g3 (positional).",
            "commonOpponentMistake": "Black plays ...d5 too early before completing development, allowing fxe5 with tempo.",
            "punishmentIdea": "After fxe5, White has a strong pawn on e5 and open f-file. Nf3 and Be2 develop with tempo.",
            "hintText": "d3 keeps all options open. You can still play f4 later, or switch to a quiet g3 setup.",
            "pawnStructure": "French-like",
            "themes": ["central-control", "space-advantage"],
            "sortOrder": 60
        },
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-trap-knight",
            "title": "Trap: Knight Fork on d5",
            "chapterName": "Traps",
            "eco": "C25",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 Nc6 3. Bc4 Bc5 4. Qg4 Qf6 5. Nd5 Qxf2+ 6. Kd1 Kf8 7. Nh3",
            "difficulty": "beginner",
            "commonness": 35,
            "priority": 70,
            "isMustKnow": False,
            "isTrap": True,
            "lineType": "trap",
            "lineSummary": "A tactical trap where White sacrifices f2 to get Nd5 with devastating threats.",
            "strategicGoal": "Play Qg4 to provoke ...Qf6, then Nd5 forks the queen and threatens Nxc7+.",
            "commonOpponentMistake": "Black takes f2+ thinking they're winning, but Nd5 creates multiple threats.",
            "punishmentIdea": "After Nd5, threats include Nxc7+ (forking rook) and Nxf6. Black can't defend everything.",
            "hintText": "Qg4 looks odd but it provokes ...Qf6. After Nd5, the queen is attacked and Nxc7+ looms.",
            "pawnStructure": "Open center",
            "themes": ["tactical-complications", "gambit-play"],
            "sortOrder": 70
        },
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-max-lange",
            "title": "Max Lange Attack Setup",
            "chapterName": "Sharp Lines",
            "eco": "C26",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 Nf6 3. Bc4 Bc5 4. d3 O-O 5. Bg5 h6 6. Bh4 d6 7. Nf3 Bg4 8. Nd5",
            "difficulty": "intermediate",
            "commonness": 45,
            "priority": 60,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "sharp",
            "lineSummary": "A Max Lange-inspired setup where White develops aggressively with Bg5 and aims for Nd5.",
            "strategicGoal": "Develop with Bg5 pinning, then jump Nd5 for a powerful outpost. f4 follows for kingside pressure.",
            "commonOpponentMistake": "Black doesn't challenge Nd5 immediately, allowing it to become a permanent fixture.",
            "punishmentIdea": "Nd5 on d5 is incredibly strong — it threatens Nxf6+ and supports c3-d4 center expansion.",
            "hintText": "Bg5 + Nd5 is the aggressive Vienna plan. The knight on d5 dominates the position.",
            "pawnStructure": "Closed center",
            "themes": ["piece-activity", "kingside-attack"],
            "sortOrder": 80
        },
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-delayed-f4",
            "title": "Delayed f4: Positional Gambit",
            "chapterName": "Core System",
            "eco": "C25",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 Nf6 3. Bc4 Nc6 4. d3 Bb4 5. f4 d6 6. Nf3 Bxc3+ 7. bxc3 O-O 8. O-O",
            "difficulty": "intermediate",
            "commonness": 55,
            "priority": 65,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "main",
            "lineSummary": "White delays f4 until after development, getting a positional gambit with the bishop pair.",
            "strategicGoal": "Allow ...Bxc3+ to get the bishop pair and open b-file. f4 opens the position for the bishops.",
            "commonOpponentMistake": "Black exchanges on c3 too early, giving White the bishop pair in an open position.",
            "punishmentIdea": "After bxc3, White has the bishop pair and semi-open b-file. f4-f5 opens diagonals for both bishops.",
            "hintText": "After ...Bxc3+ bxc3, you have doubled pawns but the bishop pair and open lines compensate fully.",
            "pawnStructure": "Doubled c-pawns",
            "themes": ["piece-activity", "kingside-attack"],
            "sortOrder": 90
        },
        {
            "openingSlug": "vienna-game",
            "slug": "vienna-game-stanley",
            "title": "Stanley Variation: 3.f4 d5",
            "chapterName": "Sharp Lines",
            "eco": "C26",
            "color": "white",
            "pgn": "1. e4 e5 2. Nc3 Nf6 3. f4 d5 4. fxe5 Nxe4 5. Nf3 Bg4 6. Qe2 Nc5 7. d4 Ne6 8. Be3",
            "difficulty": "advanced",
            "commonness": 45,
            "priority": 55,
            "isMustKnow": False,
            "isTrap": False,
            "lineType": "sharp",
            "lineSummary": "The Stanley variation where Black counters f4 with ...d5. Complex middlegame with chances for both.",
            "strategicGoal": "After fxe5, maintain the extra pawn on e5 and develop with Nf3, Qe2, d4 for a strong center.",
            "commonOpponentMistake": "Black plays ...Bg4 but doesn't follow up with ...Nc5-e6, losing coordination.",
            "punishmentIdea": "White's center (d4+e5) is powerful. If Black doesn't challenge it quickly, White dominates.",
            "hintText": "After fxe5, the pawn on e5 is your trump card. Develop behind it with d4 and Be3.",
            "pawnStructure": "Advanced e-pawn",
            "themes": ["central-control", "space-advantage"],
            "sortOrder": 100
        }
    ]
}

# Save part 1
output = {"linePacks": OPENINGS}
with open("data/new-openings-part1.json", "w") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print(f"Part 1 written: {sum(len(p['lines']) for p in OPENINGS.values())} lines across {len(OPENINGS)} openings")
